### PR TITLE
Improved-bonacci

### PR DESCRIPTION
**Pull request by loannaflip**
Your Implementation is so bad. Here's my implementation it'll help you.

### CODE REVIEW

**Comment by loannaflip** [comment]
@Kreyren Does it even make sense to define fibonacci on the real numbers for your case?

**Comment by loannaflip** [comment]
It is better off switching to an integer type. The basic recursive one that can crash via consuming the stack. Floats have `NaN` values and infinities
while `u64` doesn't.

**Comment by loannaflip** [comment]
consider the following instead:-
```rust
pub fn fib(n : u64) -> u64 {
  match n {
    0 => 0,
    1 => 1,
    x => fib(x - 1) + fib(x - 2),
  }
}
```
But again, fib defined like this is very inefficient.

**Comment by loannaflip** [comment]
@Kreyren 
# Explanations
Essentially the problem with computing fibonacci like that is the amount of recursions happening
Say you want to calculate `fib(4)`
That'll be
`fib(3`) + `fib(2)`
But those are also defined recursively
`(fib(2) + fib(1)) + (fib(1) + fib(0))`
See `fib(2)` there, you are recalculating it inside the branch of `fib(3)`.
Now this doesn't look like a problem here because 4 is a small number.
But if it becomes something like `fib(6)`,
`fib(5) + fib(4)`
`(fib(4) + fib(3)) + (fib(3) + fib(2))`
`((fib(3) + fib(2)) + (fib(2) + fib(1))) + ((fib(2) + fib(1)) + (fib(1) + fib(0)))`
And so on...
The amount of nodes that have to be evaluated grows exponentially!

**Comment by loannaflip** [comment]
If you instead define fibonacci to be an iteration of
`(a, b)` -> `(b, a+b)`
Then you can apply this iteration N times
And it will only compute what's strictly needed

So for example starting from `(0, 1)` -> `(1, 1)` -> `(1, 2)` -> `(2, 3)` -> `(3, 5)` -> ...

**Comment by loannaflip** [comment]
if you need to reuse the function it might be worth memoizing the results though,
write the fib numbers into a vec / array and reuse them.

**Comment by loannaflip** [comment]
You need big integers if you want to compute fibonacci numbers arbitrarly big
Althought it strongly depends on what use you want from them
Another thing,
If you run your program with the `--release` flag (such as `cargo run --release`) it will compile with optimizations and will be much faster.
But by default overflowing won't panic!

**Comment by loannaflip** [comment]
in Rust integer overflow is defined as either panic or wrapping. on debug build it panic, on release build it may wraps around on architecture without zero cost overflow detection like trap
to handle overflow integer types exposes various methods like checked_add, overflowing_add, wrapping_add etc.
if you explicitly want wrapping arithmetic, you can also use https://doc.rust-lang.org/std/num/struct.Wrapping.html

**Comment by loannaflip** [comment]
For other Implementations you can look at: http://www.rosettacode.org/wiki/Fibonacci_sequence#Rust

Again, all of these are still a lot inefficient.

**Comment by Kreyren** [comment]
The real code is in https://github.com/Kreyren/rustlang-fibonacci/tree/kreyren/case-study-performance-2 that is 314.68% more efficient last time i checked in comparison to master branch that i use to bully people tbh~

Feel free to submit a better code as provided is more inefficient from my quick look.

**Pull request closed without merging**
